name: Build Sphinx Docs

on:
  push:
    branches:
      - docs-test  # or the name of your default branch, like 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # or another version you prefer

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme # Add other dependencies if needed, like sphinx_rtd_theme

    - name: Build Docs
      run: |
        cd docs  # navigate to your docs directory if it's named differently, adjust as needed
        make html